{% set version = "7.4.0rc1" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  git_url: https://github.com/tpaviot/pythonocc-core.git
  git_tag: 7.4.0rc1


build:
  number: 0
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - ninja
    - cmake
    - swig >=3.0.11

  host:
    - python {{ python }}
    - occt ==7.4.0

  run:
    - occt ==7.4.0
    - python

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
  requires:
    - pyqt >=5

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
